version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'America/Denver'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /well/backups:/mnt:z
    command: -s "media;/mnt2;yes;no;no;vatican" -u "vatican;vatican" -p'
