version: '3'

services:
  samba:
    tty: true
    network_mode: bridge
    volumes:
      - /well/backups:/backups
      - /well/share:/share
    ports:
      - "139:139"
      - "445:445"
    build:
      context: .
      dockerfile: Dockerfile