version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'America/Denver'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /well/media:/mnt1:z
      - /well/backups:/mnt2:z
      - /well/share:/mnt3:z
    command: '-s "backups;/mnt2;yes;no;yes" -s "share;/mnt3;yes;no;yes" -p'
