version: '2'

services:
  minecraft-survival:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "cree8"
      SPAWN_PROTECTION: "0"
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      USE_AIKAR_FLAGS: "TRUE"
      OPS: "programmingpope"
      WHITELIST: "programmingpope,greenpoplio"
      ENFORCE_WHITELIST: "TRUE"
      MOTD: "Meow meow??"
      SEED: "3852389639702038662"
      TYPE: "FABRIC"
      VERSION: "1.19.2"
      TUNE_VIRTUALIZED: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      JVM_DD_OPTS: "disable.watchdog:true"
      AUTOPAUSE_TIMEOUT_EST: "600"
      VIEW_DISTANCE: "32"
    image: itzg/minecraft-server
    container_name: minecraft_create_mod
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - ./data:/data
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      PAUSE_IF_NO_PLAYERS: "true"
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    volumes:
    # mount the same volume used by server, but read-only
    - ./data:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - /media/backups/create-mod:/backups
    # share network namespace with server to simplify rcon access
    network_mode: "service:minecraft-survival"
