version: '2'

services:
  minecraft-survival:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "cree8"
      SPAWN_PROTECTION: "0"
      MAX_MEMORY: "3G"
      OPS: "programmingpope"
      WHITELIST: "programmingpope,greenpoplio"
      ENFORCE_WHITELIST: "TRUE"
      MOTD: "Sorry"
      SEED: "3852389639702038662
      TYPE: "FABRIC"
      TUNE_VIRTUALIZED: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      JVM_DD_OPTS: "disable.watchdog:true"
      AUTOPAUSE_TIMEOUT_EST: "600"
      VIEW_DISTANCE: "32"
    image: itzg/minecraft-server
    container_name: minecraft_create_mod
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - ./data:/data
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "12h"
      PAUSE_IF_NO_PLAYERS: "true"
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    volumes:
    # mount the same volume used by server, but read-only
    - ./data:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - /well/minecraft/create-backup:/backups
    # share network namespace with server to simplify rcon access
    network_mode: "service:minecraft-survival"
