version: '3.6'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/Denver'
      PIHOLE_DNS_: '8.8.8.8;8.8.4.4'
      DHCP_ACTIVE: 'true'
      DHCP_START: 10.9.8.7
      DHCP_END: 10.9.8.100
      DHCP_ROUTER: 10.9.8.1
      INTERFACE: 'br0'
    env_file:
     - .env
    volumes:
     - '/well/container-data/pihole/pihole:/etc/pihole/'
     - '/well/container-data/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
