services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '10.9.8.2:80:80'
      - '10.9.8.2:81:81'
      - '10.9.8.2:443:443'
    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

    volumes:
      - /var/lib/container-data/nginx/data:/data
      - /var/lib/container-data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      dockerbridge:
        ipv4_address 10.9.8.2

networks:
  dockerbridge:
    driver: bridge
    config:
      - subnet: 10.9.8.0/24
        gateway: 10.9.8.1