version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: router.home
    ports:
      - 10.9.8.1:19999:19999
    environment:
      - DOCKER_HOST=proxy:2375
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=b5c5f81e-ecc0-4de5-92f6-cdb13206bb06
    env_file:
      - .env
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /:/host/root:ro
      - /well:/host/well:ro
  proxy:
    image: tecnativa/docker-socket-proxy
    container_name: netdata_proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
