version: '2'

services:
  minecraft-creative:
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MODE: "creative"      
      SERVER_NAME: "la familia creativa"
      TYPE: "SPIGOT"
      SPIGOT_DOWNLOAD_URL: "https://cdn.getbukkit.org/spigot/spigot-1.13.2.jar"
      VERSION: "1.13.2"
      MOTD: "Now with 100% more VR"
    image: itzg/minecraft-server
    container_name: minecraft_creative
    tty: true
    stdin_open: true
    restart: always
    networks:
      - vatican-bridge
    volumes:
    - /well/containers/minecraft-creative:/data

networks:
  vatican-bridge:
    external: true
