
version: '2'

services:
  minecraft-survival:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "survival"
      SPAWN_PROTECTION: "0"
      MAX_MEMORY: "3G"
      OPS: "programmingpope"
      VERSION: "LATEST"
      MOTD: "mooo"
      SEED: "5725851600822493716"
    image: itzg/minecraft-server
    container_name: minecraft_survival3
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - /well/minecraft/survival3:/data
