version: '2'

services:
  minecraft-survival:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "survival"
      MEMORY: "2G"
      MAX_MEMORY: "4G"
      OPS: "programmingpope"
      VERSION: "1.16.4"
      MOTD: "yerp"
    image: itzg/minecraft-server
    container_name: minecraft_survival
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - /well/containers/minecraft-survival:/data
