
version: '2'

services:
  minecraft-survival:
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "survival"
      MAX_MEMORY: "6G"
      OPS: "programmingpope"
      VERSION: "1.16.5"
      MOTD: "mooo"
    image: itzg/minecraft-server
    container_name: minecraft_survival2
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
    - /well/minecraft/survival2:/data
