version: '3'

services:
  samba:
    build: .
    container_name: samba
    restart: unless-stopped
    tty: true
    network_mode: host
    volumes:
      - ./smb.conf:/etc/samba/smb.conf:ro
      - /well/backups:/backups
      - /well/share:/share
      - /well/media:/media
    